### ISSUE TITLE
`lake init` overrides existing `<PKG>.lean`

### ISSUE THREAD

**Issue by Kha** [leanprover/lake#10]
leanpkg might also do that, I don't remember :sweat_smile:

**Comment by tydeu** [comment]
@Kha yep, `leanpkg` also did this. Do we want to change that behavior?

**Comment by Kha** [comment]
Yes, I think so! We should never overwrite user data like that. Except maybe for `package.lean`, that is kind of expected for this operation I suppose.

**Comment by Kha** [comment]
Actually no, `init` on a ln existing package should be an error If it isn't already.
