### ISSUE TITLE
Lake build with dependencies require internet access 

### ISSUE THREAD

**Issue by lecopivo** [leanprover/lake#104]
Having mathlib4 as a dependency seems to break `lake build` if you are offline.

---

Reproduce:

In a clean directory:
```
lake init Test
```
Add the following to `lakefile.lean`
```
require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git"@"8f609e0ed826dde127c8bc322cb6f91c5369d37a"
```
Run `lake build` for initial build and initialization of mathlib4. 

Disconnect from the internet and run `lake build` again, results in:
```
error: stderr:
fatal: unable to access 'https://github.com/leanprover-community/mathlib4.git/': Could not resolve host: github.com
error: git exited with code 128
```

---

Tested on: `leanprover/lean4:nightly-2022-07-11`

**Comment by lecopivo** [comment]
Thanks for fixing this!

**Comment by pechersky** [comment]
I've hit this issue again, with mathlib4 and nightly 2022-10-20, when offline. This prevents the lakefile from parsing, which prevents me from being able to work on porting even when I'm offline.
