### ISSUE TITLE
Diamond version conflict not detected/reported

### ISSUE THREAD

**Issue by lovettchris** [leanprover/lake#110]
[diamond.zip](https://github.com/leanprover/lake/files/9238341/diamond.zip)

![image](https://user-images.githubusercontent.com/18707114/182272477-613f98a1-2d0e-4538-9947-77da0102baf2.png)

This builds and runs, but I have no idea which version of the csvparser it ended up using.

**Comment by tydeu** [comment]
See #70, in the next milestone there will be logging showing what version has been chosen (on a `lake update`). Regardless of version, Lake always does a best effort approach and it is up to the user to resolve conflicts.

**Comment by tydeu** [comment]
As this should be solved in the current v4.0.0, I am closing this issue.
