### ISSUE TITLE
Nix flakes are broken on v4.0.0

### ISSUE THREAD

**Issue by RaitoBezarius** [leanprover/lake#113]
It seems like v4.0.0 release broke Nix flakes, I am only able to run it with v3.2.2 using Nix.
Repro case: `nix run "github:leanprover/lake#lake" --no-write-lock-file` fails with some elaborator issue if I'm not wrong.

**Comment by Kha** [comment]
If it's something like
```
       > Lake/DSL/Meta.lean:56:34: error: application type mismatch
       >   runTermElabM none
```
Then that's simply because Lake master is not currently compatible with Lean master. The compatible branch is https://github.com/leanprover/lake/tree/runTermElabM.

**Comment by tydeu** [comment]
> Then that's simply because Lake master is not currently compatible with Lean master.

It is now. :)

**Comment by RaitoBezarius** [comment]
Indeed, thanks a lot!
