### ISSUE TITLE
Lake no longer builds dependencies of executables

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#115]
I did not debug this thoroughly, but here's a repro:
```bash
git clone https://github.com/leanprover-community/mathport
cd mathport
git checkout e16a13a76b08d7270ad25398ce3bc51bef0518ae
lake build
lake update
cp lean_packages/mathlib/lean-toolchain .
lake build
```

The last `lake build` should obviously rebuild all of mathlib4 as well as mathport, but it only rebuilds a single file:
```
Building MathportApp
error: > LEAN_PATH=./build/lib:./lean_packages/mathlib/build/lib LD_LIBRARY_PATH=/home/gebner/.elan/toolchains/leanprover--lean4---nightly-2022-08-09/lib:/nix/store/802ip579zgma3f11kq5lkypk5jpnihvf-pipewire-0.3.52-jack/lib:./build/lib /home/gebner/.elan/toolchains/leanprover--lean4---nightly-2022-08-09/bin/lean ./././MathportApp.lean -R ././. -o ./build/lib/MathportApp.olean -i ./build/lib/MathportApp.ilean -c ./build/ir/MathportApp.c
error: stdout:
./././MathportApp.lean:1:0: error: import failed, environment already contains 'Lean.NameMap.instForInNameMapProdName'
./././MathportApp.lean:3:0: error: unknown namespace 'Mathport'
./././MathportApp.lean:5:22: error: unknown identifier 'Task'
./././MathportApp.lean:5:22: error: unknown constant 'sorryAx'
./././MathportApp.lean:20:14: error: expected token
./././MathportApp.lean:28:17: error: expected ']'
error: external command `/home/gebner/.elan/toolchains/leanprover--lean4---nightly-2022-08-09/bin/lean` exited with code 1
```

**Comment by gebner** [comment]
Okay, this is even stranger because after deleting `lean_packages` and `build` I still get the error:
```
info: cloning https://github.com/leanprover-community/mathlib4 to ./lean_packages/mathlib
Building MathportApp
error: > LEAN_PATH=./build/lib:./lean_packages/mathlib/build/lib LD_LIBRARY_PATH=/home/gebner/.elan/toolchains/leanprover--lean4---nightly-2022-08-09/lib:/nix/store/802ip579zgma3f11kq5lkypk5jpnihvf-pipewire-0.3.52-jack/lib:./build/lib /home/gebner/.elan/toolchains/leanprover--lean4---nightly-2022-08-09/bin/lean ./././MathportApp.lean -R ././. -o ./build/lib/MathportApp.olean -i ./build/lib/MathportApp.ilean -c ./build/ir/MathportApp.c
error: stdout:
./././MathportApp.lean:1:0: error: unknown package 'Mathlib'
./././MathportApp.lean:3:0: error: unknown namespace 'Mathport'
./././MathportApp.lean:5:22: error: unknown identifier 'Task'
./././MathportApp.lean:5:22: error: unknown constant 'sorryAx'
./././MathportApp.lean:20:14: error: expected token
./././MathportApp.lean:28:17: error: expected ']'
error: external command `/home/gebner/.elan/toolchains/leanprover--lean4---nightly-2022-08-09/bin/lean` exited with code 1
```

**Comment by gebner** [comment]
Hmm, it works if I add `lean_lib Mathport` to the lakefile.

**Comment by tydeu** [comment]
@gebner This is because the mathport [lakefile](https://github.com/leanprover-community/mathport/blob/master/lakefile.lean) only builds a single file (`MathportApp`) it does not have an associated `lean_lib` listed.

**Comment by gebner** [comment]
I figured as much, but this doesn't seem to mentioned anywhere in the documentation.

**Comment by tydeu** [comment]
@gebner 

> I figured as much, but this doesn't seem to mentioned anywhere in the documentation.


I am not sure what you mean by this.  If a lakefile lists only an executable, Lake will only build that executable root. This seems like the intuitive expectation and the documented behavior.

The README [entry](https://github.com/leanprover/lake#binary-executables) for `lean_exe`'s `root` option mentions that "The root is built by recursively building its local imports (i.e., fellow modules of the workspace)". If there are no other `lean_lib` definitions than there are no fellow modules of the workspace (as `lean_lib` [documentation](https://github.com/leanprover/lake#lean-libraries) mentions). I am not sure what else should be said.

**Comment by tydeu** [comment]
Also, as an FYI, Lake never built dependencies of an executable without a separate library listing. The reason why the mathport lakefile probably worked prior to v4 is that it was relying on the deprecated autogenerated library (and executable) that used to be part of the `package mathport` declaration.
