### ISSUE TITLE
Add flag-sensitive build job helper for FFI code

### ISSUE THREAD

**Issue by arthurpaulino** [leanprover/lake#126]
I was trying to build a project that uses the FFI and there was a compilation error telling me to add `-fPIC` as a parameter. I tried to add it in many ways, including the right one: in the array of flags. Either way didn't work.

Turns out I just had to do `lake clean` before trying `lake build` again, which is a bit strange because I was expecting `lake build` to notice that I had a different build setup.

For more context: https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/C.20FFI.20usage/near/299865961

**Comment by tydeu** [comment]
This is because your `ffi.o` is a custom target. In order to make it rebuild upon the changing of compile flags you need to include those flags in the trace of that build (e.g., via `extraDepTrace` on `buildAfterDep`). The builtin targets for module compilation already do this (see `buildLeanO`).

**Comment by Kha** [comment]
Reinterpreting this issue as a feature request, I suppose a generic `buildO` job capturing this common pattern would be a nice addition
