### ISSUE TITLE
`lake build` modifies manifest

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#137]
This causes a build failure in mathport:
```bash
git clone https://github.com/leanprover-community/mathport
cd mathport
git checkout f071992a732b95d49b75111dfbdd9cdd9cd371dc
lake print-paths  # lake build works too but takes longer and fails
git diff          # shows modified manifest.json!
```

**Comment by gebner** [comment]
I think this happens because aesop and mathlib4 reference different revisions of std4 in their manifests.

**Comment by tydeu** [comment]
Yeah, I think your interpretation is correct. I believe this is thus the same root problem as #70.

**Comment by tydeu** [comment]
Fixed by https://github.com/leanprover/lake/pull/138 (not sure why GitHub did not automatically close it already).
