### ISSUE TITLE
`lake upload` fails to generate the tar archive

### ISSUE THREAD

**Issue by JLimperg** [leanprover/lake#143]
Version: Lean 4 nightly 2022-12-05

The first time I execute `lake upload`, it reliably fails with this error message:
```text
error: stderr:
tar: .: file changed as we read it
error: external command `tar` exited with code 1
```
The second time, it reliably succeeds.

This seems to be because Lake's child `tar` process is run in `build` (via `-C build`, so `.` in the above error message) but also drops the generated archive into `build`, which I guess changes the mtime of `build` during the archiving process. On the second try, the file already exists so `tar` is apparently happy.

Possible solutions:

- Generate the archive as a temporary file, then move it to `build` afterwards. This is probably good for atomicity anyway.
- Treat `tar` exit code 1 (which means "some files changed") as success and perhaps suppress the associated warning (`--warning=no-file-changed`).

**Comment by tydeu** [comment]
I thought I had worked around this using `--exclude` to avoid it tar capturing the resulting tart itself. It worked for me when I tested it I wonder why it does not work for you.

**Comment by tydeu** [comment]
I went and ran `lake upload` in my test project with a new build directory with no archive and `tar` did not complain about the recursion. The `--exclude` flags successfully prevent the error/warning. This, I cannot reproduce this error. @JLimperg any idea why we get different behaviors?

**Comment by JLimperg** [comment]
I just tried to reproduce again, but now it's working for me as well. Very confusing since I didn't update `tar` in the meantime. I'll close for now and re-open if I run into this again.
