### ISSUE TITLE
Lake should not recompile when local Lean build changes

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#154]
These days I often need to try out core changes on mathlib.  For that my workflow is roughly:
 1. Make change in core Lean and rebuild core Lean.
 2. Restart file server in mathlib.

This works fine without any delay until I insert step (1.5): make a git commit in core Lean.  Then Lake suddenly recompiles all of mathlib/std/etc.

The easiest way to make this work is probably to set `USE_GITHASH=OFF` in my local Lean build, and have Lake accept the empty git hash as an (impure) version.  Unfortunately, right now if Lake sees an empty git hash it falls back to hashing the Lean binary, which is a lot worse.

**Comment by tydeu** [comment]
I assume you want this to be an option, right? Because in normal cases, we do what to rebuild packages if the Lean version / binary changes.

**Comment by gebner** [comment]
> I assume you want this to be an option, right? Because in normal cases, we do what to rebuild packages if the Lean version / binary changes.

Right, you'd need to opt-in by setting `USE_GITHASH=OFF` in the cmake build.  All Lean releases come with the git revision embedded, so we're still rebuilding if the version changes.

**Comment by tydeu** [comment]
@gebner So, you are saying that Lake never check the binary and only use the `lean --githash` and treat errors or absence there as a single unique version? That seems a little unsafe, but I guess it is fine.

**Comment by gebner** [comment]
It's already the status quo.  Local builds print a nonempty githash, even if there are uncommitted changes.
