### ISSUE TITLE
`lake clean` doesn't clean dependent projects

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#155]
When running `lake clean` in mathlib, the oleans for std/aesop/etc. are not deleted.

**Comment by tydeu** [comment]
Yes, `lake clean` only cleans (deletes the build directory) of the root package (as its help states). I assume you would like it to do more? What do you think would be better behavior?

**Comment by gebner** [comment]
Yes, it should clean the non-root build directories as well imho, so that `lake clean && lake build` always gives you a fresh build. Is there a reason it doesn't delete all `build` directories?

**Comment by tydeu** [comment]
@gebner The original rational was that it is sometimes useful to navigating into dependency directories and build / edit the project separately. Thus, it may be undesirable to have root `lake clean` also clobber dependency build directories. However, I think that is enough of an edge case that your requested behavior is a much more reasonable default.

**Comment by tydeu** [comment]
However, there is a technical question about how Lake should go about deducing dependency build directories in `lake clean`. I would imagine we don't want to have `lake clean` to resolve dependencies (i.e., download ones that have not yet been downloaded), but Lake currently doesn't have a way of deducing build directories without doing that.

**Comment by gebner** [comment]
>  I would imagine we don't want to have lake clean to resolve dependencies

We already do that. :smile: Usually people want to run `lake clean` *after* `lake build`, so I don't expect the extra download to happen frequently.  I don't think we should delete the downloaded packages, just the build products.  So `lake clean && lake clean` wouldn't do the download.

In the future, we might also want to download packages on demand, i.e., only when they contain a module that is imported by something we want to build.  Then we could just check what packages have been downloaded, and clean only those.
