### ISSUE TITLE
Don't prepend to LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by locriacyber** [leanprover/lake#160]
`lake exe prog` prepends the toolchain lib path to $LD_LIBRARY_PATH. This messes up libdl significantly.

```
IO.getEnv "LD_LIBRARY_PATH" 
-- is this
/home/user/.elan/toolchains/leanprover--lean4---nightly/lib:/usr/lib:/usr/local/lib:./build/lib:./lake-packages/raylib/build/lib
```

in particular, libGL is broken with it
```
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: undefined symbol: _ZTIN4llvm19RTDyldMemoryManagerE, version LLVM_15 (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open iris: /usr/lib/dri/iris_dri.so: undefined symbol: _ZTIN4llvm19RTDyldMemoryManagerE, version LLVM_15 (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: undefined symbol: _ZTIN4llvm19RTDyldMemoryManagerE, version LLVM_15 (search paths /usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

This is because the libLLVM.so in lean's toolchain is of different version from the system LLVM.

**Comment by tydeu** [comment]
@locriacyber Adding to `LD_LIBRARY_PATH` is required for things like precompile modules to work with the executed programs. If there are clashes between the Lean toolchain libraries and the system libraries that already has good chance of breaking things.

However, to make your use case possible, we can add an option to a `lean_exe` like `noExecToolchainLibs` to prevent `lake exec` from doing this on just those executable.

**Comment by locriacyber** [comment]
Can you add it to the back of `LD_LIBRARY_PATH`?

**Comment by tydeu** [comment]
@locriacyber Reviewing my own code a bit more, Lake already appends to `LD_LIBRARY_PATH`
https://github.com/leanprover/lake/blob/f59328e3d9b23f0266e40ceb31cb4353d9bf0dae/Lake/Config/Workspace.lean#L168-L169
Furthermore, Lake does not even add a toolchain path to this variable. Thus, I believe the elan shim may be invisibly adding it itself. To test this, I ran:
```lean
echo '#eval IO.getEnv "LD_LIBRARY_PATH"' | lean --stdin
```
When I run this I my Windows machine I get the toolchain path (implying the shim is adding it automatically). In which case, this is actual an problem with Lean, not Lake. Thus, I think you want to file an issue over on the [lean4](https://github.com/leanprover/lean4) repository.

**Comment by locriacyber** [comment]
Thanks
