### ISSUE TITLE
Show warning on unclean dependencies

### ISSUE THREAD

**Issue by Kha** [leanprover/lake#167]
If any checkout in `lake-packages` differs from the pinned commit, we should print a warning, especially as this can lead to cache misses in mathlib.

**Comment by Kha** [comment]
Yes, exactly!

An interesting follow-up question might be whether dependencies should be local git repos at all (instead of e.g. checkouts of user-wide bare repos, or direct tarball fetches in the case of GitHub) but that is probably low priority.

**Comment by tydeu** [comment]
@Kha Having gone to implement this, I rediscovered that, even on build, we reset the dependency to the pinned commit (if it is on something else). So, they can never differ. Would you still like Lake to print a warning if it does such an update? Or is it good as is?

**Comment by Kha** [comment]
Ah, then I must have misremembered my original request: "unclean" usually means that the *working directory* differs from the checked-out commit. We can probably ignore untracked files(?) but any local change to a dependency is concerning and should generate a warning.
