### ISSUE TITLE
possible process contention issue with multiple dependencies

### ISSUE THREAD

**Issue by semorrison** [leanprover/lake#17]
In trying to build the `mathport` `mathlib`, I run into a variety of apparently non-deterministic errors, either of the form

```
failed to write '././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathport/./lean_packages/mathlib/./build/lib/Mathlib/Tactic/Basic.olean': 2 No such file or directory
```

or 

```
libc++abi.dylib: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
```

Steps to reproduce
===

Create `Dockerfile` containing
```
FROM ubuntu

USER root

# Set timezone to UTC to avoid prompts from tzdata.
RUN TZ=UTC ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
# Install prerequisites.
RUN apt-get update && \
    # Lean4 prerequisites:
    apt-get install -y git libgmp-dev cmake ccache gcc-10 g++-10 && \
    apt-get clean
# We need curl to download elan
RUN apt-get install -y curl
# Lake additionally requires some header files for the compiler:
RUN apt-get install -y build-essential

# create a non-root user
RUN useradd -m lean

USER lean
WORKDIR /home/lean

SHELL ["/bin/bash", "-c"]
# set the entrypoint to be a login shell, so everything is on the PATH
ENTRYPOINT ["/bin/bash", "-l"]

# make sure binaries are available even in non-login shells
ENV PATH="/home/lean/.elan/bin:/home/lean/.local/bin:$PATH"

# install elan
RUN curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- -y && \
    . ~/.profile && \
    elan toolchain uninstall stable

RUN git clone https://github.com/leanprover/lake && \
    cd lake && \
    ./build.sh

ENV PATH="/home/lean/lake/build/bin/:$PATH"

# Clone the `test-mathport` repository.
RUN git clone https://github.com/leanprover-community/test-mathport
WORKDIR /home/lean/test-mathport

RUN make download-release
```
This will download `elan`, builds `lake` from source, collects the (850mb!) artifact from `mathport`.

Build the docker image with `docker build -t test-mathport .`
Open a command line in the docker image with `docker run -it test-mathport`.
Run `lake build`, and wait for the errors.

Hints as to diagnosis
===

One thing I can see that is potentially going wrong is that `lake` is updating the same dependency multiple times.
Filtering on `trying to update` we see
```
mathlib: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathlib to revision lake
mathport: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathport to revision master
mathlib: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathlib to revision lake
mathport: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathport to revision master
mathlib: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathlib to revision lake
mathport: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathport to revision master
mathlib: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathlib to revision lake
mathport: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathport to revision master
mathlib: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathport/./lean_packages/mathlib to revision lake
mathlib: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathlib to revision lake
mathport: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathport to revision master
mathlib: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathlib to revision lake
mathport: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathport to revision master
mathlib: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathport/./lean_packages/mathlib to revision lake
mathlib: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathport/./lean_packages/mathlib to revision lake
mathlib: trying to update ././Lib4/liquidbin/./../mathbin/./../leanbin/./lean_packages/mathlib to revision lake
```

**Comment by Kha** [comment]
The first error seems easily explainable with your observations, but the second one is concerning. You wouldn't happen to be able to capture a stack trace for it, e.g. as in https://stackoverflow.com/a/26315770/161659?

**Comment by semorrison** [comment]
@Kha, here is [a crash report](https://gist.github.com/semorrison/490496060bbcfa8ea635f3d7be1ac824).

**Comment by Kha** [comment]
Thanks! Are you sure it's related though? It is somewhat older (09/19) and the error message is related but doesn't seem to quite match. In any case, I'm afraid we can't help with bugs in `bash` :) .

**Comment by semorrison** [comment]
@Kha, sorry, I updated it. I had the wrong thing on the clipboard and didn't double check. :-(

**Comment by tydeu** [comment]
@semorrison I have figured out that this is, in fact, at least in part, a `lake` bug. 

Lake is currently building dependencies in parallel and  package dependencies are also currently transitive, Neither is inherently wrong on its own, but together they create a problem: each dependency is built simultaneously by each of its parents. Thus, if a dependency is more than one level deep, the same package is being multiple times simultaneously, creating the contention issues you are seeing.

This was not caught earlier because the dependency examples I have thus far are only 1 level deep.

**Comment by tydeu** [comment]
@semorrison  The combination of 3a7f842b18e32377706be464eb8d9c98e312539c and d81d0bae45c51b3e875500dcd595bb5d8676482b should have fixed this issue. I have verified that I can build [test-mathport](https://github.com/leanprover-community/test-mathport) with Lake on the 10-02 nightly using the updated Mathlib and Mathport.

**Comment by semorrison** [comment]
Thanks. Works for me too!
