### ISSUE TITLE
Error when getting cache for new project

### ISSUE THREAD

**Issue by miguelmarco** [leanprover/lake#177]
When trying to create a new project, I get the following error:

```
user2@debian:~$ lake +leanprover/lean4:nightly-2023-07-20 new lean math
info: Downloading lean-toolchain
user2@debian:~$ cd lean
user2@debian:~/lean$ lake update
cloning https://github.com/leanprover-community/mathlib4.git to lake-packages/mathlib
cloning https://github.com/EdAyers/ProofWidgets4 to ./lake-packages/proofwidgets
cloning https://github.com/mhuisi/lean4-cli.git to ./lake-packages/Cli
cloning https://github.com/gebner/quote4 to ./lake-packages/Qq
cloning https://github.com/JLimperg/aesop to ./lake-packages/aesop
cloning https://github.com/leanprover/std4 to ./lake-packages/std
user2@debian:~/lean$ lake exe cache get
error: no such file or directory (error code: 2)
  file: ./././Lean/Data/Json/Parser.lean
```

**Comment by tydeu** [comment]
@miguelmarco `cache` is a mathlib tool, and not part of Lake. So, you can likely get more help if you report this on the mathlib4 [Zulip channel](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4) or [issue board](https://github.com/leanprover-community/mathlib4/issues). However, the fact that it cannot find [`Lean.Data.Json.Parser`](https://github.com/leanprover/lean4/blob/367b38701fb9cca80328624a016c3b3acfd5e2cd/src/Lean/Data/Json/Parser.lean) is concerning. There may be a problem with Lake buried here as well. Still, I would suggest duplicating this issue in the other venues to get more eyes on it.

**Comment by Kha** [comment]
`lean` is one of the more unfortunate package names to choose - that is, it collides with the built-in `Lean` package

**Comment by miguelmarco** [comment]
> `lean` is one of the more unfortunate package names to choose - that is, it collides with the built-in `Lean` package. Please try again with a different name.

I see, that seems to be the cuplrit. Using another name for the project, it works.

**Comment by Kha** [comment]
Ideally Lake could check that the roots of all packages are disjoint and give a nicer error message otherwise

**Comment by tydeu** [comment]
@Kha This requirement is not always true as some packages have roots for libraries/utilities that can overlap with peer libraries without issue (e.g., mathlib's `Cache`)

**Comment by Kha** [comment]
Isn't `Cache` a separate root? But to be more exact, I meant that for each pair of packages, their sets of roots (of public libraries?) should be disjoint.

**Comment by tydeu** [comment]
@Kha My point was that multiple packages could have something named `Cache` and get along fine (as they are not expected to be imported by dependent packages). However, a public/private distinction could certainly help here.

**Comment by digama0** [comment]
I think we should require those to be distinct as well, as dependent packages might want to refer to mathlib's `Cache` as well, it is not intended to be private.

**Comment by tydeu** [comment]
@digama0 Referring to it (e.g., via `lake exe cache` is different from importing it. Reference does not require distinctness, importing does (due to Lean's import algorithm).

**Comment by tydeu** [comment]
@digama0 

> It would be better if it could be namespaced under `Mathlib`, but the current lake ontology wouldn't really allow that IIUC, `Mathlib` is a library and shouldn't have exes under it...?

No, you can mix them all if you want. After all, this is what Lake does. `Lake.Main` -- the executable -- is distinct from what you get from `import Lake` -- despite them both being under the same library `Lake`.

The only caveat is that right now you cannot easily have two libraries with the clashing root because there is no well-defined selection order for which library the module will belong to.
