### ISSUE TITLE
`lake new` created project can not `import Mathlib`  on Gentoo Linux

### ISSUE THREAD

**Issue by geometrylearner** [leanprover/lake#178]
It's an issue in VScode editor on Gentoo Linux Workstation(remote access with VScode) where I check the Lean4 by creating  **test.lean** in a new project named by **Firstlemmaprover**.

I create a test project named Firstlemmaprover with `lake new Firstlemmaprover math` then run `lake exe cache get` to download the required dependencies as the [.](https://leanprover-community.github.io/install/project.html). But the **test.lean** := 
"""import Mathlib.Topology.Basic
#check TopologicalSpace"""
had been reported "unknown package 'Mathlib'“.

Then I tried to build the dependencies locally by `lake update` and then `lake build` but  of course not worked.

The `lake` on My Gentoo is installed by shell ``curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh``. The same `test.lean` had been checked correctly in the existed project(folk) **mathematics_in_lean** as introduced in install documentation.

I wonder whether I can start my Lean4 experiment from scratch instead starting with an existed project on my Gentoo Workstation.

Thanks.

**Comment by Kha** [comment]
Apparently resolved in https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/.E2.9C.94.20lean4.2Fmathlib4.20import.20issue.20on.20Gentoo

**Comment by geometrylearner** [comment]
Thanks for your reply, it's me, fixed. Now, I can run several Lean4 Projects with different dependencies on single remote Gentoo Server. My habit of vscode/conda/jupyter mislead me. There is a strict logic requirement that {Lean4 Projects} => {Lean4 Servers} => {Lean4 deps} one-to-one.
