### ISSUE TITLE
`lake env` requires a lakefile

### ISSUE THREAD

**Issue by digama0** [leanprover/lake#179]
There are use cases for `lake env` even when not being run in a lean project, e.g. to set up the linker flags for an invocation of a program which depends on lean but is not actually a lean project (this came up in https://github.com/digama0/lean-rs, which is a rust project which dynamically links to lean, not a lean project).

**Comment by tydeu** [comment]
From the [Zulip discussion](https://leanprover.zulipchat.com/#narrow/stream/113488-general/topic/FFI.20External.20Object/near/385322481), Lake should also add core Lean libraries to shared library path.

**Comment by Kha** [comment]
A slight danger here is that it makes it harder to notice that one called `lake env` in the wrong directory. Semantically speaking, a package-independent command could go in elan instead.

**Comment by tydeu** [comment]
@Kha note that `lake serve` is already package independent (when it fails back to `lean --server`). So, I do not think having package-optional commands is completely unrealistic for `lake`. We could print a warning here, but that may clutter the command output undesirably.

**Comment by Kha** [comment]
Yes, if this is deemed a legitimate use case, it should not produce a warning. I didn't think about `server` but to be fair that is not a command ever invoked by end users.

**Comment by tydeu** [comment]
Closed by leanprover/lean4#2428 (not sure why this did not close when it was merged).
