### ISSUE TITLE
Mark this repo as deprecated?

### ISSUE THREAD

**Issue by DenisGorbachev** [leanprover/lake#186]
Since it's merged into lean4, maybe it's better to mark it as deprecated & add link to [src/lake](https://github.com/leanprover/lean4/tree/master/src/lake) to README?

**Comment by semorrison** [comment]
Can we please do this? It is unhelpful that attempts to find lake documentation end up at this abandoned repo.

**Comment by digama0** [comment]
One thing that came up in discussion with Mac is that the lake readme is still the primary source of reference documentation on the lake DSL. Of course the lake embedded in lean also has this readme, but it is now even harder to find if you are not already planning to contribute to lake.

**Comment by tydeu** [comment]
We also need to transfer all the issues before we archive the repository.

**Comment by semorrison** [comment]
So the README here should be replaced with a "Please see <link to the embedded README>" prior to archiving.
