### ISSUE TITLE
Add a `lake lean` CLI

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#24]
It would be great to have a `lake lean` command that calls `lean` with the correct `LEAN_PATH` and plugin arguments set.

**Comment by gebner** [comment]
> It would also not require spawning a separate process, which I think would be nice.

This is both a blessing and a curse.  If lake would in the future include more libraries such as curl or openssl, then it's easy to get clashes (or have unwanted VM overrides).

I agree that more specific commands can be helpful, but I think there's room for both the porcelain and the plumbing here.

> Furthermore, while I am not sure what your plan is, but I imagine much of the functionality might even be split into separate executables in Lean itself when that part of it is rewritten in Lean.

In that case I'd of course want a lake command for every lean command.

> I can easily see concerning anti-patterns that could emerge where users do lake lean --server instead of lake server

I don't think that any user every called `lean --server` manually.  This is all set up by the editor plugins.  Which reminds me that we should migrate them to `lake server`...

The concrete anti-pattern that I'm trying to get rid of with this feature request is `env LEAN_PATH=build/lib lean` (which will break if you change the working directory, or add dependencies, or enable plugins, or switch from leanpkg to lake).  And yes, I use `--trust` (which is not an option) and all the other options, in particular when I bother to run a file manually.

> bring the package (and it dependencies) up to date before running lean or just use the current state of the package?

I would like the `lake lean` command to just run lean with the correct options and no building (so that I can run it even if something fails to compile, etc.).  Again, my usecase is very much temporary/debugging/etc.  If I want proper dependency management, I'd add the file to the lakefile.

A specialized command to run separate files like the `lake elab` could then build the dependencies and the imported modules (with opt-out).

(I hate to bikeshed, but elab feels like the wrong word.  I've never heard anybody say they elaborate a Lean file, they run it or compile it.  So I think `lake run` or `lake compile` or even `lake script` would be better.)

**Comment by tydeu** [comment]
> (I hate to bikeshed, but elab feels like the wrong word. I've never heard anybody say they elaborate a Lean file, they run it or compile it. So I think `lake run` or `lake compile` or even `lake script` would be better.)

I personally have no problem with bikeshedding, so feel free to do so. While this may be true, the technical fact of the matter is what such a command does is simply run `Elab.runFrontend` on the contents of the file in question, so I think preserve that fact in the name is reasonable. Also, the use of `run`/`script` would already clashes with the existing Lake scripting mechanism (see the [Scripts](https://github.com/leanprover/lake#scripts) section of the README) and 'compile' is most certainly *not* what is being done, so those names are not an option.

**Comment by tydeu** [comment]
>  And yes, I use `--trust` (which is not an option) and all the other options, in particular when I bother to run a file manually.

The funny thing is from looking at the source of the lean executable, it doesn't appear that the trust level is actually passing into the elaborator frontend. The trust level is a field of the environment, but `Elab.runFrontend` doesn't take an environment as an input, (and the the lean executable does just call it -- see [`run_new_frontend`](https://github.com/leanprover/lean4/blob/2e36e362cbbd4c4b23c6407392a3d79bcb813e1c/src/util/shell.cpp#L322-L326) and its [use](https://github.com/leanprover/lean4/blob/2e36e362cbbd4c4b23c6407392a3d79bcb813e1c/src/util/shell.cpp#L628)). It instead instead creates a new one with the default trust level of 0 (see the code for [`runFrontend`](https://github.com/leanprover/lean4/blob/2e36e362cbbd4c4b23c6407392a3d79bcb813e1c/src/Lean/Elab/Frontend.lean#L100), [`processHeader`](https://github.com/leanprover/lean4/blob/2e36e362cbbd4c4b23c6407392a3d79bcb813e1c/src/Lean/Elab/Import.lean#L23), and [`mkEmptyEnvironment`](https://github.com/leanprover/lean4/blob/2e36e362cbbd4c4b23c6407392a3d79bcb813e1c/src/Lean/Environment.lean#L277-L286)) , so I don't think that option actually does anything.

**Comment by tydeu** [comment]
> > It would also not require spawning a separate process, which I think would be nice.
> 
> This is both a blessing and a curse. If lake would in the future include more libraries such as curl or openssl, then it's easy to get clashes (or have unwanted VM overrides).

I am not sure what you mean here? Clashes with what / where?

**Comment by gebner** [comment]
> > > It would also not require spawning a separate process, which I think would be nice.
> > 
> > This is both a blessing and a curse. If lake would in the future include more libraries such as curl or openssl, then it's easy to get clashes (or have unwanted VM overrides).
> 
> I am not sure what you mean here? Clashes with what / where?

There are several types of clashes:

1. At least on Linux, I believe that you cannot load two libraries with the same symbols.  So if lake links against OpenSSL 1.1, and I want to write an FFI wrapper for OpenSSL 1.2, then I can't use this command.

2. A similar issue, but with a Lean flavor.  The Lean VM will look up native implementations of functions by their symbol name, and then use use the native implementation if present.  So if the lake binary has a `l_Lake_createParentDirs` symbol, then any call to a function with the name `Lake.createParentDirs` will be redirected to the lake version.  In other words, you can't use this new command to try out changes to the `Lake.createParentDirs` function.

3. Global state.  A lot of libraries require some kind of global initialization.  If lake already initializes a library, then the user program will fail if it does that again.  (A particularly heavy user of global initialization is Lean itself, see 2.)

**Comment by tydeu** [comment]
For now, I think the current `lake env lean` is a sufficient solution for this issue, so I will close it. However, I do still have the idea of a `lake elab` stored away for future.
