### ISSUE TITLE
after modifying lean-toolchain, need to manually lake clean

### ISSUE THREAD

**Issue by semorrison** [leanprover/lake#26]
When updating the version of Lean 4 being used in a repository (e.g. mathlib) by editing `lean-toolchain`, I would expect that `lake build` rebuilds everything. However it returns immediately, and you need to first `lake clean` to discard oleans to actually get a build.

**Comment by tydeu** [comment]
@semorrison it definitely shouldn't be doing that after https://github.com/leanprover/lake/commit/7cde2a45a23fdb87ffac8e6643c2662bf1d4e1ec. What version of Lake/Lean are you using? I also can not reproduce this on the latest Lake -- testing on an example rebuilds everything as expected.

**Comment by semorrison** [comment]
I can reproduce as follows:

```
git clone https://github.com/leanprover-community/mathlib4.git
cd mathlib4
git checkout 64f9c43eb9a75fb4c5989ac711623d06e9696e60
lake --version # says: Lake version 3.0.0-pre (Lean version 4.0.0-nightly-2021-11-07)
lake build
echo "leanprover/lean4:nightly-2021-11-10" > lean-toolchain
lake --version # says: Lake version 3.0.0-pre (Lean version 4.0.0-nightly-2021-11-10)
lake build  # returns immediately
```

**Comment by tydeu** [comment]
@semorrison Sorry, but I can't reproduce. Running those same commands for me result in lake rebuilding the whole library each time.

**Comment by tydeu** [comment]
For posterity, this issue was further discussed [on Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/lake.20problem.2C.20perhaps.20macos.20specific.3F/near/261096361) where the source of the bug was found.
