### ISSUE TITLE
OpaqueTarget.collectList / collectArray don't exist

### ISSUE THREAD

**Issue by semorrison** [leanprover/lake#30]
The README and Lake/Config/Package.lean have advice to use `OpaqueTarget.collectList` or `OpaqueTarget.collectArray` to assemble a list of targets into one. However these functions don't exist, as far as I can see.

(There is `Target.collectList / collectArray`, and also for `ActiveTarget`.)

**Comment by tydeu** [comment]
@semorrison  Oops, yeah, they disappear in a refactor a long time ago -- the appropriate functions are ``Target.collectOpaqueList` and `Target.collectOpaqueArray`. Will also fix this in the big README update commit (along with your PRs).
