### ISSUE TITLE
Breaks when changing git repo url

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#31]
Running `lake build` fails after changing the url of a git dependency.

```lean
import Lake
open Lake DSL

package foo {
  dependencies := #[{
    name := "mathlib",
    src := Source.git "https://github.com/dselsam/mathlib4.git" "5366ff9252f9001fc10e610795efd259fd4b8dc6"
    -- src := Source.git "https://github.com/leanprover-community/mathlib4.git" "bc7ef82aae2ab89845a4e496bb9f1aac08679828"
  }],
}
```

1. `lake build`
2. Comment out the other src field.
3. `lake build`

And you get the following error message:
```
mathlib: trying to update ./lean_packages/mathlib to revision bc7ef82aae2ab89845a4e496bb9f1aac08679828
error: git exited with code 128
error: build failed
```

It would also be great if lake could show the actual error message from git instead of just the error code.

**Comment by dselsam** [comment]
> It would also be great if lake could show the actual error message from git instead of just the error code.

Seconded -- I get `git exited with code 128` fairly often for seemingly different reasons, and it would be much easier to debug with a more detailed message.
