### ISSUE TITLE
Use the system linker if given custom linker flags

### ISSUE THREAD

**Issue by Kha** [leanprover/lake#36]
This seems to be the weak consensus from https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/C.20FFI.20usage, but I'm open to further discussion.

**Comment by tydeu** [comment]
What do you mean by the "system linker"? Do you mean `ld`, `cc`, or `c++` (or something else)?

**Comment by Kha** [comment]
`getBuiltinLinkerFlags` returns `-Wl,` prefixes, so I suppose it would have to be `cc`. If someone wants to link in C++ code, I think it should be their responsibility to specify `c++` instead.

**Comment by tydeu** [comment]
@Kha So is the suggestion to just switch from `leanc` to `cc` when `moreLinkArgs` is not-empty? Or is there more configuration that needs to be done to get the build to then work?

**Comment by Kha** [comment]
It should be equivalent if you add the `getBuiltinLinkerFlags` into the mix, though it wouldn't work if someone wanted to specify linker flags without having a system toolchain installed of course. I don't know how realistic that is; most such use cases should probably be covered by new Lake flags, such as `useLTO := true` (which affects both compilation and linking anyway). But maybe an explicit flag `useSystemLibraries := true` would be better?

**Comment by Kha** [comment]
We can also move the discussion back to Zulip

**Comment by tydeu** [comment]
@Kha so I am trying to replace invoking `leanc` with just invoking the bundled `clang` directly. Just passing `getBuiltinLinkerFlags` is insufficient to get this to work. From what I can tell I also need to change the sysroot with `--sysroot=<lean-sysroot>/include/clang` -- is there anything else I need as well?

**Comment by tydeu** [comment]
Also, I have had a number of problems when attempting to link using an external linker (e.g., both `cc` and `clang`) on Window MSYS2 s with `getBuiltinLinkerFlags`.

1. MSYS2 build essentials do not come with `libc++` or `libc++abi`, they must be installed separately
2. MSYS2 requires `libc++abi` to come *before* `libc++` (it currently comes after it in the flags)
3. The `-pthread` option is unused when building with `clang`

I am currently get a segfault when running the built executable after a successful link (and I am now working on debugging that).

**Comment by tydeu** [comment]
Having toyed around some more, I think my question is: @Kha, why does `leanc` need to change the `--sysroot`? Could it instead just add the bundled libraries to the library path (via `-L`) or pass the library file directly (if one is worried about the library search preferring the native libraries instead of the bundled ones). With an unchange `--sysroot`, system libraries could still  be found by the bundled `clang`/`leanc` when specified by the user.

**Comment by Kha** [comment]
There should be no need for additional flags, which must mean that `getBuiltinLinkerFlags` is incomplete. One issue is that in https://github.com/leanprover/lean4/blob/ba8372110968e6a695d6cb6558e717d19e6bfc7f/script/prepare-llvm-mingw.sh#L41, only the last flag should be internal probably. Changing the sysroot should not be necessary; in fact, I'd prefer to use the bundled linker with the "system sysroot" as mentioned in https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/C.20FFI.20usage/near/262868754. I can take a look tomorrow.

**Comment by Kha** [comment]
> why does `leanc` need to change the `--sysroot`

`crtbegin.o` etc are found via the sysroot.

**Comment by tydeu** [comment]
> There should be no need for additional flags, which must mean that `getBuiltinLinkerFlags` is incomplete. One issue is that in https://github.com/leanprover/lean4/blob/ba8372110968e6a695d6cb6558e717d19e6bfc7f/script/prepare-llvm-mingw.sh#L41, only the last flag should be internal probably.

Sounds good! Also, `-lgmp` should probably not be in that list (especially statically) as it is part of the `getBuiltinLinkerFlags`. The flags I used to get a direct invocation of the bundled linker to work in the CI on all platforms are [here](https://github.com/leanprover/lake/blob/b9578d68da3e7a6ade21c36baef0bf18519d0332/Lake/Build/Targets.lean#L85-L93) in the PR. I probably missed some ones needed for special configurations, though.

**Comment by Kha** [comment]
Closing in favor of leanprover/lean4#890.
