### ISSUE TITLE
`Glob.pushModules` fails on hierarchical modules

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#42]
If you set ``libGlobs := #[Glob.submodules `Mathlib]`` in `lakefile.lean`, then `lake` fails in the `pushSubmodules` function with:
```
error: no such file or directory (error code: 2)
  file: ././Mathlib/Data/Mathlib/Data
error: build failed
```

Also, `Glob.getModules` has two `Glob` arguments.

**Comment by tydeu** [comment]
@gebner 

> Also, `Glob.getModules` has two `Glob` arguments.

No, [it](https://github.com/leanprover/lake/blob/90e4ae7d51a9c0ecffab9057ad9a2bbfba7ed2d6/Lake/Config/Glob.lean#L55) does not?

**Comment by gebner** [comment]
> @gebner
> 
> > Also, `Glob.getModules` has two `Glob` arguments.
> 
> No, [it does not](https://github.com/leanprover/lake/blob/90e4ae7d51a9c0ecffab9057ad9a2bbfba7ed2d6/Lake/Config/Glob.lean#L55)?

The `self` argument is unused. :smile:
