### ISSUE TITLE
Including other local files?

### ISSUE THREAD

**Issue by kunigami** [leanprover/lake#45]
Sorry if this is documented elsewhere, but how do I include other local files? I have the following structure:

    project/
      Main.lean
      Project.lean
      Lib.lean
      lakefile.lean

With `Main.lean` as:

    import Lib
    import Project

    def main : IO Unit :=
    IO.println s!"Hello, {hello}!"

I run

    lake build

And get:

    ././Main.lean:1:0: error: unknown package 'Lib'

I tried adding the files as explicit dependencies, but I think it's expecting directories:

    import Lake
    open Lake DSL

    package project {
      -- add configuration options here
      dependencies := #[
        -- { name := `a, src := Source.path ("./Lib.lean") }
      ]
    }

How can I include `Lib.lean`?

**Comment by tydeu** [comment]
There are two ways to do this:

1) put `Lib.lean` in the `Project` subdirectory **(standard way)**

If you organize the project like so

```
project/
  Main.lean
  Project/
    Lib.lean
  Project.lean
  lakefile.lean
``` 

you can then import `Lib.lean` in `Main.lean` via `import Project.Lib`.

2) add `Lib` as an additional package root

With your original organization:

```
project/
  Main.lean
  Project.lean
  Lib.lean
  lakefile.lean
``` 


You can instead add `Lib` to the `libRoots` configuration option. It will allow you to also import modules relative to a the top-level `Lib`

```
package project {
  libRoots := #[`Project, `Lib`]
}
```

With this, `import Lib` will import `Lib.lean`.

**Comment by tydeu** [comment]
Fyi,, generally questions like this would be asked on the [Lean 4 Zulip](https://leanprover.zulipchat.com/#narrow/stream/270676-lean4).

**Comment by kunigami** [comment]
Thanks for the quick answer and the FYI!
