### ISSUE TITLE
Listing stderr output as `error:` is confusing

### ISSUE THREAD

**Issue by Kha** [leanprover/lake#54]
See e.g. https://leanprover.zulipchat.com/#narrow/stream/270676-lean4/topic/New.20Member. Build tools do not usually differentiate between stdout and stderr in logs.

**Comment by tydeu** [comment]
@Kha what would be your solution? Should `stderr` be logged as info instead?

**Comment by Kha** [comment]
Ideally stdout and stderr should not be separated at all, but I suppose we don't have the API to do that yet. How about simply labelling them with `stdout: ` and `stderr: ` instead?
