### ISSUE TITLE
Large startup delay with many dependencies

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#65]
On my desktop, every additional dependency seems to add 250ms to the startup time (it's almost twice as much on my laptop).  For example calling `lake env true` on [doc-gen4](https://github.com/leanprover/doc-gen4) takes more than a second (as it has four dependencies).

If I read the profiling results correctly, then this is mostly due to module imports.  Every lakefile executes `import Lake` separately.  And starting with the second lakefile (i.e. all the dependencies) the mmap-optimization no longer works, so importing is even slower.

Just running `import Lake` the first time takes around 130ms here:
```bash
time echo import Lake | lean --stdin
```

**Comment by tydeu** [comment]
"And starting with the second lakefile (i.e. all the dependencies) the mmap-optimization no longer works," Isn't that a bug with Lean then?

**Comment by gebner** [comment]
> > And starting with the second lakefile (i.e. all the dependencies) the mmap-optimization no longer works,
> 
> Isn't that a bug with Lean then?

It's not really a bug, just a small possible optimization.  Everything still works as it should, but it (only) adds around 100ms (as well extra memory) per lakefile.  Implementing the optimization would not even cut the lake runtime in half.

The bigger issue is that we're compiling multiple lakefiles at all, since importing alone (excluding olean loading time) costs around 130ms per lakefile.

**Comment by tydeu** [comment]
> The bigger issue is that we're compiling multiple lakefiles at all, since importing alone (excluding olean loading time) costs around 130ms per lakefile.

How do you propose fixing this? This seems inherently necessary to process multiple packages.

**Comment by gebner** [comment]
> > The bigger issue is that we're compiling multiple lakefiles at all, since importing alone (excluding olean loading time) costs around 130ms per lakefile.
> 
> How do you propose fixing this? This seems inherently necessary to compile multiple lakefiles to process multiple packages.

I'm not sure if there's an obvious and straightforward fix here.  But I can think of a number of things we could do.

*Reduce imports.*  The fewer modules a lakefile imports, the fast the importing process obviously.  The typical lakefile does not require the elaborator, so we could remove the transitive import from `Lake` to `Lean.Elab.Frontend`.  This is [easy to try out](https://github.com/gebner/lake/commit/91f498118c4cffe496716bcce0aa68c278ebee5d) and results in a 40% speedup (on doc-gen4).

*Import only once.*  The expensive part is the call to `importModules` (in `runFrontend`).  However this function is (for typical lakefiles) always called with the argument ``[{module := `Lake}]``.  Caching this function call should eliminate most of the extra cost of compiling additional lakefiles.

*Allow mmapping the same olean file multiple times.*  This would reduce memory usage and import time if the mitigations above don't help.  (needs to be done in core, obviously)

*Precompile lakefiles.*  There is no good reason to compile the lakefile again every time lake is called.  If we compiled all lakefiles into oleans, then we'd only need to do one import.  We could even compile the lakefile into a shared object, which is much faster to load.  Lakefiles are also getting larger and more complex.  This change however requires that the identifiers in the lakefiles don't clash (either for oleans or shared objects), for example by requiring that each lakefile is in a separate namespace.  This is a breaking syntax change though.

*Speed up importing.*  Clearly it would be nice if importing didn't take that long to begin with.  From what I can tell, at the moment the main cost center is finalizing the environment extensions after importing.  This will be a big issue with mathlib, where the binport already takes almost two seconds to import on my laptop and that's missing like 90% of the attributes.  Coupled with the other issues of the attributes/environment extensions---you can't inspect them (see recent issues with doc-gen4) and many attributes are extremely limited (can only be applied to declarations in the current file, cannot be scoped)---I expect that we will need to rework that part sooner or later.  Finally, Sebastian is also working on a module system which might reduce the modules that need to be imported or at least the size of the oleans.

**Comment by gebner** [comment]
One more:

*Call lake less often.*  This doesn't really help with command-line usage, and I don't think we should implement an sbt-style repl for lake.  But we could conceivably eliminate the need for `lake print-paths`, which would make it faster to open files in an editor.

**Comment by tydeu** [comment]
Thanks for all the suggestions! 

> _Reduce imports._ ]..] This is [easy to try out](https://github.com/gebner/lake/commit/91f498118c4cffe496716bcce0aa68c278ebee5d) and results in a 40% speedup (on doc-gen4).

This looks great to me! Feel free to PR the change and I'll merge it.

> _Import only once._ The expensive part is the call to `importModules` (in `runFrontend`). However this function is (for typical lakefiles) always called with the argument `` [{module := `Lake}] ``. Caching this function call should eliminate most of the extra cost of compiling additional lakefiles.

I am a little confused as to how this would would work? For one, are you sure that caching the result of `importModules` is safe?

> _Precompile lakefiles._ 

Yep, this is already on my TODO list.

> I don't think we should implement an sbt-style repl for lake. 

Actually, there was part of me that was thinking that this may be a good idea. Start-up cost is Lake's major performance problem at the moment, and this would mitigate that.

> But we could conceivably eliminate the need for `lake print-paths`, which would make it faster to open files in an editor.

Yeah, I think it might be better if the language server just imported Lake directly (or vice versa) rather than use `lake print-paths`.

**Comment by gebner** [comment]
> > _Reduce imports._ ]..] This is [easy to try out](https://github.com/gebner/lake/commit/91f498118c4cffe496716bcce0aa68c278ebee5d) and results in a 40% speedup (on doc-gen4).
> 
> This looks great to me! Feel free to PR the change and I'll merge it.

Done, #66.

> > _Import only once._ The expensive part is the call to `importModules` (in `runFrontend`). However this function is (for typical lakefiles) always called with the argument `` [{module := `Lake}] ``. Caching this function call should eliminate most of the extra cost of compiling additional lakefiles.
> 
> I am a little confused as to how this would would work?

Basically we'd have to inline `runFrontend` and `processHeader` in lake.  I guess we can put the cache in a global variable.

> For one, are you sure that caching the result of `importModules` is safe?

Yes, it is.  It is just an environment.  The only thing you're not allowed to do is call `env.freeRegions` on it.

> > _Precompile lakefiles._
> 
> Yep, this is already on my TODO list.

Great!

> > I don't think we should implement an sbt-style repl for lake.
> 
> Actually, there was part of me that was thinking that this may be a good idea. Start-up cost is Lake's major performance problem at the moment, and this would mitigate that.

In my personal experience, a repl is much less ergonomic than the current interface.  IDEs need to manage the background process (and that part is flaky even in IntelliJ).  The readline support is never as good as in the shell.  You always have to remember to `reload`.  Specifying extra command-line arguments is a pain since you're not in the shell.  The ergonomics are so bad that they even implemented a server more now for sbt, where you have an sbt server instance running in the background and `sbt foo` connects to the server...

**Comment by tydeu** [comment]
> The ergonomics are so bad that they even implemented a server more now for sbt, where you have an sbt server instance running in the background and `sbt foo` connects to the server...

In that case, I we could have Lake build server instead.

**Comment by tydeu** [comment]
This issue is quite stale and suggested fixes have been generally implemented upstream (e.g.,, leanprover/lean4#2573), so I am closing this issue.
