### ISSUE TITLE
Updating should use manifests from dependencies

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#70]
Say you have three packages, then updating `C` (or adding the `B` dependency the first time) should take the version of `A` from `B/lean_packages/manifest.json`.
 * `A`
 * `B`, which depends on `A`
 * `C`, which depends on `B`

(The current behavior is that updating C upgrades both A and B to the latest revision, typically breaking B in the process.)

This is crucial for using manifests with anything that depends transitively on mathlib.  For example if A=mathlib, B=lean-liquid, and C=yourownproject.  Projects like lean-liquid bump the mathlib version every couple of weeks, using any other mathlib version will break.

**Comment by tydeu** [comment]
@gebner This feature would mean that `lake update` only updates the top-level package's direct dependencies, right?

**Comment by gebner** [comment]
> My simplest solution to all of this is to append dependency's manifests to the top-level package's with their entries mark `inherited` and not update such dependencies during `lake update`.

"... but instead replace them with the current entry from the dependency's manifest."  Otherwise sounds good to me.
