### ISSUE TITLE
Make `FilePath` relative to its package

### ISSUE THREAD

**Issue by xubaiw** [leanprover/lake#8]
I have trouble in importing binding FFI packages with lake. I make [a simple example](https://github.com/xubaiw/lake-ffi-import-example), which is largely taken from lake examples to make it clear.

```sh
~/lake-ffi-import$ tree
.
├── README.md
├── bar
│   ├── Bar.lean
│   ├── build
│   │   ├── ir
│   │   └── lib
│   └── package.lean
└── ffi
    ├── c
    │   └── add.cpp
    ├── lib
    │   └── Add.lean
    └── package.lean

10 directories, 10 files
```

There are two packages:
The `ffi` package is just a duplicate of lake ffi example, and the `bar` package simply calls `ffi`.
But when I try to build the `bar` package, lake cannot recognize the correct path of `add.cpp`.

```sh
~/lake-ffi-import/bar$ lake build-bin
> LEAN_PATH=./../ffi/./build/lib lean -R ./../ffi/./. -o ./../ffi/./build/lib/Add.olean -c ./../ffi/./build/ir/Add.c ./../ffi/./lib/Add.lean
no such file or directory (error code: 2)
  file: c/add.cpp
> leanc -c -o ./../ffi/./build/ir/Add.o ./../ffi/./build/ir/Add.c
> LEAN_PATH=./build/lib:./../ffi/./build/lib lean -R ./. -o ./build/lib/Bar.olean -c ./build/ir/Bar.c ././Bar.lean
././Bar.lean:1:0: error: unknown package 'Ffi'
You might need to open '/Users/xubaiw/lake-ffi-import' as a workspace in your editor
././Bar.lean:3:11: error: unknown identifier 'IO'
././Bar.lean:3:11: error: unknown constant 'sorryAx'
././Bar.lean:4:15: error: expected command
external command lean exited with status 1
Build failed with errors, the last of which was:
external command lean exited with status 1
```

It seems that lake try to find the path of `add.cpp` in current pacakge (`bar`), but it should search for that in original package (`ffi`).

**Comment by tydeu** [comment]
Oops! Yep, this is a major issue. Sadly, fixing this in a pure `PackageConfig` is non-trivial, so I will have to some thinking on how best to accomplish it.

**Comment by tydeu** [comment]
I have updated the `ffi` example to resolve this problem (and added an `ffi-dep` example to show it works). Right now, I just pass the `pkgDir` down to the library target, but I am hoping to, in the future, support a cleaner solution. However, such a thing may take some time, so until then, this workaround will have to be sufficient.
