### ISSUE TITLE
lake build emits confusing warning when it comes from a dependency

### ISSUE THREAD

**Issue by Julian** [leanprover/lake#81]
Given the `lakefile.lean`:

```lean
import Lake
open Lake DSL

package foo {
}

lean_lib Foo {
}

require LSpec from git
  "https://github.com/yatima-inc/lspec.git"@"cd0e7191b42bf8f0114ab063c446457b134cafd6"
```

Running `lake build` (from `Lean (version 4.0.0, commit a802544c9005, Release)`) produces:

```
⊙  lake build                                            julian@Airm ●
warning: Package targets are deprecated. Add a `lean_exe` and/or `lean_lib` default target to the package instead.
```

So I modified the file to instead have:

```
@[defaultTarget]
lean_lib Foo {
}
```

and was confused as to why the error doesn't go away.

But it's because it comes from building the `LSpec` dependency, and [its own lakefile](https://github.com/yatima-inc/LSpec/blob/cd0e7191b42bf8f0114ab063c446457b134cafd6/lakefile.lean#L4-L6) not being ready for the new syntax. It'd definitely be helpful to see the location of the warning.

**Comment by Kha** [comment]
I took the liberty to adjust the original issue's title :)
