### ISSUE TITLE
`lake update` doesn't update

### ISSUE THREAD

**Issue by gebner** [leanprover/lake#84]
0. Publish project `a`.
1. In project `b`, add a dependency `require a from ".../a.git"@"master"`
2. In project `b`, run `lake update`.
3. Push some commits to `a`.
4. In project `b`, run `lake update`.

The last `lake update` does nothing (with todays Lean nightly).  I would expect `lake update` to pick up the latest commit from the master branch.

**Comment by tydeu** [comment]
Do you happen to have a nice way to test his programmatically? That would really help me in narrowing down the problem.

**Comment by Kha** [comment]
For what it's worth, this seems to work fine with me using `Lake version 3.1.1 (Lean version 4.0.0-nightly-2022-06-17)`, updating `aesop` repeatedly

**Comment by gebner** [comment]
> Do you happen to have a nice way to test his programmatically?

Here you go:

```bash
#!/usr/bin/env bash
set -ex

export ELAN_TOOLCHAIN=leanprover/lean4:nightly-2022-06-28

rm -rf a b

lake new a
pushd a
git add .
git commit -am 'first commit in a'
a=$(pwd)
popd

lake new b
pushd b
cat >>lakefile.lean <<EOF
require a from git "$a" @ "master"
EOF
lake update
git add .
git commit -am 'first commit in b'
popd

pushd a
echo def hello2 := 42 >>A.lean
git commit -am 'second commit in a'
popd

pushd b
lake update
git diff
popd
```

The last `lake update` should update the `a` dependency to `second commit in a`, but it does nothing as shown by the empty output of `git diff`.

> For what it's worth, this seems to work fine with me

You should probably check in the `manifest.json`.  The bug here obviously doesn't happen if the `manifest.json` is missing because then Lake will just clone the latest version of the dependency.

**Comment by Kha** [comment]
> You should probably check in the `manifest.json`.

Whoops, it should be there, thanks for noticing. The repo is a scrubbed mirror of an internal repo, in which `update` with manifest.json seemed to work fine. It's unfortunate that there's now an important file in a directory (`lean_packages`) that used to be ignored completely, this broke our mirroring setup.
